# Site settings

title: RFCOA
description: Site for the Riverside Famrs Condominium Owners' Association
cover: assets/images/aerial.jpg
logo: assets/images/barn_sized.png
#favicon: assets/images/favicon.png
#baseurl: "/hanuman/" # the subpath of your site, e.g. /blog/ or / for root
#url: "https://samanyougarg.com" # the base hostname & protocol for your site
# paginate:	5 # The number of posts to show per page on your homepage

theme: hanuman

# Social
#facebook: facebook
#twitter: twitter
#github:  github

#Additional Pages
#about: about
#contact: contact
#privacy-policy: privacy-policy
overdue: overdue

permalink: /:title

# Google Analytics
#analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

# Settings for rake task
safe: False
lsi: False
username: hoffmanc #github username
repo: rfcoa #github repository
branch: master #branch
#relative_source: ../ #source directory
#destination: ../hanuman-pages/ #destination directory
#production_url:  https://samanyougarg.com/
#source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
